name: psiko_test_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/photo1.jpg
    - assets/images/photo2.jpg
    - assets/images/photo3.jpg
  uses-material-design: true
  
